alt_cap:
  outputs:
    dev:
      dataset: ecommerce_transform_01
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: key.json
      location: EU
      method: service-account
      priority: interactive
      project: alt-school-capstone-project-1
      threads: 1
      type: bigquery
  target: dev